sonar.projectKey=palcarazm_bs-darkmode-toggle
sonar.organization=palcarazm
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

sonar.coverage.exclusions=**/*.config.{js,cjs,mjs},**/Gruntfile.{js,cjs},docs/**,test/**,cypress/**,src/test/**,src/main/js/**,src/main/ts/**/index.*.ts,src/main/ts/types/**
sonar.cpd.exclusions=test/**,cypress/**,src/test/**