name: Report a bug
description: Tell us about a bug or issue you may have identified.
title: "Provide a general summary of the issue"
labels: [bug]
assignees: "-"
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Provide a summary of the issue and what you expected to happen, including specific steps to reproduce.
    validations:
      required: true
  - type: textarea
    id: reduced-test-case
    attributes:
      label: Reduced test cases
      description: Include links [reduced test case](https://css-tricks.com/reduced-test-cases/) links or suggested fixes using [CodePen](https://codepen.io/).
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system(s) are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Android
        - iOS
        - Linux
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: What version of Bootstrap Darkmode Toggle are you using?
      placeholder: "e.g., v1.0.0"
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
        - Opera
  - type: input
    id: browser-version
    attributes:
      label: What version of the browser are you using?
      placeholder: "e.g., v5.1.0"
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: Something more you want to say?
    validations:
      required: false
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report.
