name: Cypress Tests

on:
  push:
    branches:
      - "v*"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "v*"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
